export const metadata = {
    title: 'Create hahah App',
    description: 'Generated by create next app',
  }
export default function Page(){
    return(
        <div>
            page
        </div>
    )
}